CREATE TABLE STND_TERM (
    TERM_NM VARCHAR(200) NOT NULL,
    TERM_ENG_NM VARCHAR(200) NOT NULL,
    TERM_DESC VARCHAR(500) NULL,
    TERM_ENG_ABR_NM VARCHAR(100) NOT NULL,
    PRIMARY KEY (TERM_NM)
);

COMMENT ON TABLE STND_TERM IS '표준 용어';
COMMENT ON COLUMN STND_TERM.TERM_NM IS '용어명 (한글)';
COMMENT ON COLUMN STND_TERM.TERM_ENG_NM IS '용어 영문명';
COMMENT ON COLUMN STND_TERM.TERM_DESC IS '용어 설명';
COMMENT ON COLUMN STND_TERM.TERM_ENG_ABR_NM IS '용어 영문 약어명 (단어약어_단어약어)';
