DROP TABLE IF EXISTS STND_WORD;

CREATE TABLE STND_WORD (
    WORD_NM VARCHAR(100) NOT NULL,
    WORD_ENG_NM VARCHAR(100) NOT NULL,
    WORD_DESC VARCHAR(500) NULL,
    WORD_ENG_ABR_NM VARCHAR(20) NOT NULL,
    PRIMARY KEY (WORD_NM)
);

-- 테이블 및 컬럼 코멘트 추가
COMMENT ON TABLE STND_WORD IS '표준 단어';
COMMENT ON COLUMN STND_WORD.WORD_NM IS '단어명 (한글)';
COMMENT ON COLUMN STND_WORD.WORD_ENG_NM IS '단어 영문명';
COMMENT ON COLUMN STND_WORD.WORD_DESC IS '단어 설명';
COMMENT ON COLUMN STND_WORD.WORD_ENG_ABR_NM IS '단어 영문 약어명';
